femto/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("finance/",include("finance.urls"))
]

finance/urls.py
from django.urls import path
from finance.views import User_register, User_login, create_goal, get_goals , home, logout_view

app_name = "finance"
urlpatterns = [
    path('register/', User_register,name="register"),
    path('login/', User_login,name="login"),
    path('logout/', logout_view,name="logout"),
    path('create-goal/', create_goal,name="create_goal"),
    path('get-goals/', get_goals,name="get_goals"),
    path('home/', home,name="home"),
    
]

finance/models.py
from django.db import models
from django.contrib.auth.models import User

class Goal(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    total_amount = models.DecimalField(max_digits=10, decimal_places=2)
    goal_date = models.DateField()

finance/forms.py
from django import forms
from .models import Goal
import datetime

class GoalForm(forms.ModelForm):
    class Meta:
        model = Goal
        fields = ['total_amount', 'goal_date']
        widgets = {
            'goal_date': forms.DateInput(attrs={'type': 'date'})
        }
    def clean_goal_date(self):
        goal_date = self.cleaned_data['goal_date']
        current_date = datetime.date.today() + datetime.timedelta(days=30)

        if goal_date <= current_date:
            raise forms.ValidationError("Goal date must be at least one month from today.")

        return goal_date

finance/views.py
from django.shortcuts import render, redirect ,HttpResponse
from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.forms import AuthenticationForm
import datetime

from .forms import GoalForm
from .models import Goal

@login_required
def home(request):
    goals = Goal.objects.filter(user=request.user)
    return render(request, 'finance/home.html', {'goals': goals})

@csrf_exempt
def User_register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('finance:home')
    else:
        form = UserCreationForm()
    return render(request, 'finance/register.html', {'form': form})

@csrf_exempt
def User_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('finance:home')
    else:
        form = AuthenticationForm()
    return render(request, 'finance/login.html', {'form': form})

@login_required
def create_goal(request):
    if request.method == 'POST':
        form = GoalForm(request.POST)
        if form.is_valid():
            goal = form.save(commit=False)
            goal.user = request.user
            # Calculate monthly deposit value

            total_amount = goal.total_amount
            goal_date = goal.goal_date
            current_date = datetime.date.today()
            
            months_remaining = (goal_date.year - current_date.year) * 12 + (goal_date.month - current_date.month)
            monthly_deposit = total_amount / months_remaining
          
            goal.total_amount = monthly_deposit
            goal.save()
            return redirect('finance:home')
    else:
        form = GoalForm()
    return render(request, 'finance/create_goal.html', {'form': form})

@login_required
def get_goals(request):
    goals = Goal.objects.filter(user=request.user)
    return render(request, 'finance/goals.html', {'goals': goals})
def logout_view(request):
    logout(request)
    return redirect('finance:home')

finance/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Personal Finance App</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <!-- Add your custom CSS links here -->
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="{% url 'finance:home' %}">Personal Finance App</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'finance:create_goal' %}">Create Goal</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'finance:get_goals' %}">Goals</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'finance:logout' %}">logout</a></li>
                    {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'finance:register' %}">Register</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'finance:login' %}">Login</a></li>
                        {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container mt-4">
        {% block content %}
        {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Add your custom JavaScript links here -->
</body>
</html>

finance/templates/finance/create_goal.html
{% extends 'base.html' %}

{% block content %}
  <h2>Create Goal</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Create Goal</button>
  </form>
{% endblock %}

finance/templates/finance/goals.html
{% extends 'base.html' %}

{% block content %}
  <h2>Goals</h2>
  {% if goals %}
    <ul class="list-group">
    {% for goal in goals %}
      <li class="list-group-item">{{ goal.total_amount }} - {{ goal.goal_date }}</li>
    {% endfor %}
    </ul>
  {% else %}
    <p>No goals found.</p>
  {% endif %}
{% endblock %}

finance/templates/finance/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Saving Goals</h2>
  {% if goals %}
    <ul class="list-group">
    {% for goal in goals %}
      <li class="list-group-item">{{ goal.total_amount }} - {{ goal.goal_date }}</li>
    {% endfor %}
    </ul>
  {% else %}
    <p>No goals found.</p>
  {% endif %}

  <a class="btn btn-primary mt-5" href="{% url 'finance:create_goal' %}">Create New Goal</a>
{% endblock %}

finance/templates/finance/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

finance/templates/finance/register.html
{% extends 'base.html' %}

{% block content %}
  <h2>Register</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Register</button>
  </form>
{% endblock %}